version: "2.2"

services:
 
  postgres:
  
    image: postgres:15.3
    container_name: postgres_email
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_PASSWORD=email
      - POSTGRES_USER=email
      - POSTGRES_DB=email
    volumes:
      - /tmp/pg
    profiles:
    - postgres
    - default
  
  app1:
    image: email-build
    container_name: emailserver
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILE=postgres
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/email
    profiles:
    - postgres
  app2:
    image: email-build
    container_name: emailserver
    depends_on:
      - postgres
    ports:
      - "8888:8080"
    environment:
      - SPRING_PROFILE=default
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/email
      - MQ_CONN_NAME=host.docker.internal
    profiles:
    - default 
volumes:
    postgres:
     external: true 
  
