version: "2.2"

services:

  postgres:
    image: postgres:15.3
    container_name: postgres_customer
    ports:
      - "5444:5432"
    environment:
      - POSTGRES_PASSWORD=customer
      - POSTGRES_USER=customer
      - POSTGRES_DB=customer_hdfc
    #command: docker volume create postgres  
    volumes:
     - /tmp/pg  
    profiles:
    - default
  

  app2:
    image: customer-service-build
    container_name: customer-service
    depends_on:
      - postgres
    ports:
      - "6666:8080"
    environment:
      - SPRING_PROFILE=default
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/customer_hdfc
      - MQ_CONN_NAME=host.docker.internal
    profiles:
    - default  

  
